# Напишите ваш .gitlab-ci.yml здесь
# Файл должен называться pipeline.yml (без точки в начале), чтобы не конфликтовать
# с настоящим .gitlab-ci.yml вашего курсового репозитория.
#
# См. README.md для полного списка требований.

stages: []
